services:
  broker:
    image: apache/kafka:3.8.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      #KAFKA_KRAFT_MODE: "true"  # 启用 Kraft 模式以取代 Zookeeper，默认为true
      KAFKA_NODE_ID: 1   # Kafka 节点的唯一 ID
      KAFKA_PROCESS_ROLES: broker,controller # 配置Kafka的角色，服务器将同时充当代理和控制器，如果没有设置，则将处于 ZooKeeper 模式。
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093 # 配置 Kafka 的监听接口
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # 定义控制器使用的监听器名称
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT # 定义监听器的协议映射
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093 # 配置控制器投票者
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # 设置偏移量主题的复制因子
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # 定义事务状态日志的复制因子
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1    # 事务日志的最小同步副本
      #KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1  # 设置分区数
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"  # 数据文件存储目录
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"  # 用于 broker 之间通信的监听器名称
      #KAFKA_MIN_INSYNC_REPLICAS: 1  # 最小同步副本数
      #KAFKA_BROKER_ID: 1  # Broker 的唯一 ID
      #KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,state.change.logger=INFO"  # 定义特定日志类别的日志级别
    volumes:
      - ./data/kafka:/var/lib/kafka/data  # 持久化 Kafka 数据到本地目录
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - broker
    environment:
      DYNAMIC_CONFIG_ENABLED: "TRUE"